---
name: Ruff

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of ruff
        uses: astral-sh/ruff-action@v3
      - name: Ruff check
        run: ruff check --fix
      - name: Ruff format
        run: ruff format
